name: Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        uses: actions/setup-python@v2

      - name: Configure Git
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build and publish package
        run: |
          make
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u toolquarry --password-stdin
          docker build -t docker.pkg.github.com/toolquarry/binary_to_decimal/binary_to_decimal:latest .
          docker push docker.pkg.github.com/toolquarry/binary_to_decimal/binary_to_decimal:latest
